<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-LFPM515" failures="0" tests="1" name="Day17.InvocationAssign" time="1.019" errors="1" timestamp="24 Aug 2023 12:56:08 GMT" skipped="0">
  <testcase classname="Day17.InvocationAssign" name="logintest" time="1.019">
    <error message="Method Day17.InvocationAssign.logintest() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method Day17.InvocationAssign.logintest() didn't finish within the time-out 1000
at java.base@17.0.7/java.lang.Throwable.fillInStackTrace(Native Method)
at java.base@17.0.7/java.lang.Throwable.fillInStackTrace(Throwable.java:798)
at java.base@17.0.7/java.lang.Throwable.<init>(Throwable.java:293)
at java.base@17.0.7/java.lang.Exception.<init>(Exception.java:85)
at java.base@17.0.7/java.lang.RuntimeException.<init>(RuntimeException.java:81)
at app//org.openqa.selenium.remote.http.netty.NettyHttpHandler.makeCall(NettyHttpHandler.java:63)
at app//org.openqa.selenium.remote.http.netty.NettyHttpHandler$$Lambda$125/0x0000000800e3fd80.execute(Unknown Source)
at app//org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at app//org.openqa.selenium.remote.http.AddSeleniumUserAgent$$Lambda$266/0x0000000800e7f090.execute(Unknown Source)
at app//org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at app//org.openqa.selenium.remote.http.Filter$$Lambda$126/0x0000000800e44000.execute(Unknown Source)
at app//org.openqa.selenium.remote.http.netty.NettyHttpHandler.execute(NettyHttpHandler.java:48)
at app//org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at app//org.openqa.selenium.remote.http.AddSeleniumUserAgent$$Lambda$266/0x0000000800e7f090.execute(Unknown Source)
at app//org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at app//org.openqa.selenium.remote.http.Filter$$Lambda$126/0x0000000800e44000.execute(Unknown Source)
at app//org.openqa.selenium.remote.http.netty.NettyClient.execute(NettyClient.java:97)
at app//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:115)
at app//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:96)
at app//org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:68)
at app//org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:163)
at app//org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:196)
at app//org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:171)
at app//org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531)
at app//org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:227)
at app//org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:154)
at app//org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:107)
at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:87)
at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82)
at app//org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:50)
at app//Day17.InvocationAssign.logintest(InvocationAssign.java:16)
at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:40)
at java.base@17.0.7/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- logintest -->
</testsuite> <!-- Day17.InvocationAssign -->
